### ISSUE TITLE
Improve error handling in data uploader

### ISSUE THREAD

**Issue by mstreit** [Caleydo/ordino#101]
When the user selects a file that cannot be read by the uploader (e.g., a PDF or excel file) there is no error that indicates to the user what went wrong.

**Comment by sgratzl** [comment]
or try to prevent it, see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-accept

**Comment by sgratzl** [comment]
part of https://github.com/Caleydo/ordino_uploaded_data/commit/8c5a3d5513634b83cc6b61ea89c074c733b98b3b
