### ISSUE TITLE
think about in-place tutorials

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/ordino#102]
e.g. based on http://introjs.com/

**Comment by lehnerchristian** [comment]
some possibilities:
- http://introjs.com/ (open source; but prices for commercial use?)
- https://www.walkme.com/ (not free; no price on website)
- https://zurb.github.io/joyride/ (open source)
- https://github.com/pickhardt/Guiders-JS (open source; example: https://en.wikipedia.org/wiki/Main_Page?tour=test)

**Comment by sgratzl** [comment]
as far as I understood most of these libraries are for explaining the basic interface components but are not helping the user to guide them through an example. It is a good starting point

**Comment by mstreit** [comment]
implemented in https://github.com/Caleydo/tdp_bi_bioinfodb/issues/513
