### ISSUE TITLE
advanced named sets

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/ordino#104]
in the current version the named sets just store the set of rows that are listed. 

In an advanced version, we could store the whole LineUp setup
 * visible columns
 * visible scores + parameters
 * combined scores
 * applied filters

**Comment by zichner** [comment]
Wouldn't that be the same as storing the entire session?

**Comment by sgratzl** [comment]
moved to https://github.com/datavisyn/tdp_core/issues/13
