### ISSUE TITLE
don't let user add non-existing strings to the search fields

### ISSUE THREAD

**Issue by mstreit** [Caleydo/ordino#107]
![image](https://user-images.githubusercontent.com/4129755/27961260-70a7b5ee-632e-11e7-9140-c6bac04d1fc5.png)

The behavior is also confusing during typing. 
![image](https://user-images.githubusercontent.com/4129755/27961293-858fe102-632e-11e7-9666-e5c0bada5746.png)
Is it necessary to show the current (possibly non-existing) search string as part of the drop-down list?

**Comment by sgratzl** [comment]
see also https://select2.github.io/examples.html#tags

**Comment by sgratzl** [comment]
I investigated it a bit: 

`tags`: true means that the user can add additional know existing items to the list
`tokenSeparators: [' ']` also allows the user to quickly add multiple tags by adding the separator inbetween

what can work and includes a validation of the pasted elements

``` 
tags: true,
tokenizer: this.tokenize.bind(this),
tokenSeparators: [' '],
createTag: () => null, //no automatically created tags = effectivly disables tags: true

private tokenize(query: { term: string}, options: any, addSelection: (item: ISelect2Item)=>void) {
    const term = query.term.trim();
    if (term.length === 0) { //early stop
      return query;
    }
    const arr = term.split(/[; \t\n]/);
    const last = arr[arr.length-1]; //save the last one
    if (arr.length > 1) { //just auto add tokens if we have more than one
      arr.forEach((v) => {
        console.log(v);
        const t = parseInt(v, 10);
        if (!isNaN(t)) { //some kind of validation (can be asynchronous)
          setTimeout(() => {
            addSelection({id: v, text: `Text${v}`, idType: resolve('dummy')}); //since we are not using createTag we can add new items easily
          }, 500);
        }
      });
    }
    console.log('last', last);
    return { //return the last one such that the user can continue to enter things
      term: last
    };
  }
```
