### ISSUE TITLE
set favicon for ordino platform

### ISSUE THREAD

**Issue by mstreit** [Caleydo/ordino#108]
decide whether we want to use caleydo or datavisyn favion

**Comment by sgratzl** [comment]
or create a new targid discovery icon

**Comment by lehnerchristian** [comment]
maybe in the same style as the Caleydo / Phovea logo, but without the missing piece on the right side, that it looks more like an O?

**Comment by mstreit** [comment]
yes, we need to come up with an ordino logo. please use the caleydo logo for now as favicon.
