### ISSUE TITLE
No distinction between very small values and NaN in ranking of computed scores

### ISSUE THREAD

**Issue by zichner** [Caleydo/ordino#12]
To reproduce:
1. Open list of all cell lines
2. Add score column for relative copy number of gene `ERBB2`
3. Sort cell lines according to ERBB2 copy number (ascending)

-> cell line `Becker` has a very small value (`1.10`) and gets ranked within cell lines that do not have copy number data and thus have score `NaN`
It would be expected that all cell lines with score `NaN` are ranked together (preferably at the end of the list)

**Comment by sgratzl** [comment]
see aösp https://github.com/Caleydo/lineupjs/issues/167

**Comment by zichner** [comment]
I strongly believe the minimal value should still have a (very thin) bar. See my detailed reply in the lineup issue.
Is there anything speaking against it?

**Comment by zichner** [comment]
It was decided in the last TC that for now the focus is on visually encoding missing values.
Afterwards we will decide if very small values should have a bar or not.

**Comment by sgratzl** [comment]
see https://github.com/Caleydo/lineupjs/issues/168#issuecomment-326271944

**Comment by sgratzl** [comment]
> Afterwards we will decide if very small values should have a bar or not.

if we want to create a bar for small values it is just an configuration of the underlying mapping. Currently for the scores the minimal value will be mapped to 0 = no bar and the maximal value to 1 = full bar. However, if more semantics about some scores are known, for example a known absolute minimal value, the mapping can be improved.
