### ISSUE TITLE
lineup buttons should look the same as others

### ISSUE THREAD

**Issue by mstreit** [Caleydo/ordino#121]
This is how they appear now:
![image](https://user-images.githubusercontent.com/4129755/28120264-cd706338-6717-11e7-9edf-85c97d72a634.png)

This is how they are supposed to look:
![image](https://user-images.githubusercontent.com/4129755/28120227-b151a63a-6717-11e7-833f-da1f0b2b2261.png)

There is also a change in the appearance when I zoom in our out:
![image](https://user-images.githubusercontent.com/4129755/28120291-dc85bf26-6717-11e7-9ea4-50dfbbe87cb3.png)

**Comment by sgratzl** [comment]
current proposed version: 

![greenshot_2017-07-20_11-41-31](https://user-images.githubusercontent.com/4129778/28411245-772ecd28-6d40-11e7-97d7-a1f8fbea1dc2.png)

**Comment by mstreit** [comment]
looks good

**Comment by sgratzl** [comment]
for my taste it takes quite a lot of horizontal space, especially since in my configuration the fourth (upload) button is currently missing

**Comment by sgratzl** [comment]
alternative: 
![image](https://user-images.githubusercontent.com/4129778/28412494-a965d3e6-6d44-11e7-9263-2486fac8e47d.png)
