### ISSUE TITLE
add tooltips to show/hide provenance graph and lineup icons  

### ISSUE THREAD

**Issue by mstreit** [Caleydo/ordino#123]

**Comment by sgratzl** [comment]
see https://github.com/phovea/phovea_clue/issues/121

**Comment by sgratzl** [comment]
lineup icons = LineUp Buttons I assume or the LineUp toolbars for each column?

**Comment by sgratzl** [comment]
@lehnerchristian please add the tooltips to the lineup ranking buttons

**Comment by mstreit** [comment]
Yes, I meant the three buttons on the top right of LineUp in Ordino.

**Comment by lehnerchristian** [comment]
done in https://github.com/Caleydo/ordino/pull/122/commits/bfd8843a243f0d09e876fd7c68b51875ace3ca1b
