### ISSUE TITLE
"submit issue" link in report bug dialog points to non existing page

### ISSUE THREAD

**Issue by mstreit** [Caleydo/ordino#125]
In the public version the submit issue link points to https://github.com/phovea/ordino_public/issues/new which does not exist.

![image](https://user-images.githubusercontent.com/4129755/28202696-dd84738a-6876-11e7-83a9-aa036915fb4d.png)

**Comment by sgratzl** [comment]
fixed https://github.com/Caleydo/ordino_public/commit/8855a3e760ce5fc462fabb0552fc2e215af4d9a5
