### ISSUE TITLE
Sorting box plot columns by "Mean" does not work

### ISSUE THREAD

**Issue by zichner** [Caleydo/ordino#13]
Box plot columns give the option to sort them by "Mean". However, the mean is not calculated while computing the columns, therefore, the sorting cannot work.
Therefore, please removing "Mean" from the sorting chooser.

**Comment by sgratzl** [comment]
see https://github.com/Caleydo/lineupjs/issues/231

**Comment by mstreit** [comment]
@sgratzl, the LineUp issue is already closed. Does that mean that the daily build should contain the fix already?

**Comment by sgratzl** [comment]
needs to be tested

**Comment by zichner** [comment]
"Mean" is not present any more and the other choices still work as expected. Thanks.
