### ISSUE TITLE
create database Benchmark test app

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/ordino#154]
a simple website that supports to trigger REST requests that will finally end up in database queries. 

other features
 * parallel requests to simulate load of multiple users
 * timeout settings (need for the api for that)
 * store custom requests in localStorage so that the same user can reuse it
 * list all queries + what we know about replacements and filters

**Comment by sgratzl** [comment]
-> https://github.com/datavisyn/dbbenchmark

![greenshot_2017-08-31_18-22-03](https://user-images.githubusercontent.com/4129778/29934028-f8f86aee-8e79-11e7-9186-0b4d0a0a6301.png)

**Comment by sgratzl** [comment]
current feature set
 * paste a list of rest urls collected e.g. via a logging tool
 * export results as lineup ranking
 * use any score dialog to create another rest api url
 * run queries in parallel
 * automatic retry of failed queries

**Comment by zichner** [comment]
Very Cool!
Is this accessible from BI?
