### ISSUE TITLE
Add "disclaimer" to Oncoprint detail view

### ISSUE THREAD

**Issue by zichner** [Caleydo/ordino#16]
In order to avoid misunderstandings regarding the correctness of the information shown in the Oncoprint detail view, please add the following statement:

> Please note: 
> * The indicated copy number states are only estimates, which can be affected by sample purity, ploidy, and other factors.
> * The indicated alteration prevalences are only estimates, which can be affected by incomplete data and small sample numbers.

**Comment by sgratzl** [comment]
![2017-02-22 11_25_28-target discovery platform](https://cloud.githubusercontent.com/assets/4129778/23208186/5386e678-f8f4-11e6-8c6b-139a9cec5beb.png)
