### ISSUE TITLE
How to map ensembl ids to gene symbols?

### ISSUE THREAD

**Issue by thinkh** [Caleydo/ordino#167]
I wrote a function that converts the ensembl ids into gene symbols for selections. The result looks like this:

![grafik](https://user-images.githubusercontent.com/5851088/29464594-9e9bff54-8436-11e7-84c6-87f98d6ce165.png)

The problem I noticed afterwards: I imported the mapping call from the [targid_boehringer repo](https://github.com/Caleydo/ordino/blob/e6d69f6c74aa473d85b33de2924689d57d9d59ec/src/Targid.ts#L23) and [used it here](https://github.com/Caleydo/ordino/blob/e6d69f6c74aa473d85b33de2924689d57d9d59ec/src/Targid.ts#L475).

 * Do you have any ideas how to make the mapping call globally available?
 * Is there a mapping for the [public ordino data](Caleydo/ordino_public) available?
 * Or if all this is not possible, how I can move this call to the targid_boehringer repo?

The only availability is to hand it over in the [Ordino options](https://github.com/Caleydo/ordino/blob/e6d69f6c74aa473d85b33de2924689d57d9d59ec/src/AOrdino.ts#L23) and [pass it down to the Targid instance](https://github.com/Caleydo/ordino/blob/e6d69f6c74aa473d85b33de2924689d57d9d59ec/src/Ordino.ts#L24). But this looks a bit complicated.

**Comment by sgratzl** [comment]
Ordino doesn't know anything about genes

**Comment by thinkh** [comment]
Yes, I know. That's why I'm asking how to move this function to one of the other repos, but keep the functionality.

**Comment by lehnerchristian** [comment]
I think you would want to have the function defined as an extension in the targid_common plugin and load it wherever you need it (similar to the `importPostProcessor` extension in that repo, but without the `newData` and `newConfig` stuff)
I think you already knew that...
