### ISSUE TITLE
Copy number class mapping for aggregated score column is missing

### ISSUE THREAD

**Issue by fastapis** [Caleydo/ordino#172]
### Steps to reproduce

1. select any gene set
2. add aggregated score column (cell line or tissue)
3. select data type: copy number class
4. select aggregation: frequency

### Observed behavior
* copy number class is categorial - amplification, deep deletion, normal, unknown
* ordino calculates a frequency although no mapping is provided (presumably of deep deletion)

### Expected behavior
* e.g. tick box or other input that defines the event(s)/category for which the frequency should be calculated

**Comment by sgratzl** [comment]
Issue moved to [Caleydo/tdp_bi_bioinfodb #615](https://github.com/Caleydo/tdp_bi_bioinfodb/issues/615) via [**ZenHub**](https://www.zenhub.com/)
