### ISSUE TITLE
Collapsed groups don't open on click

### ISSUE THREAD

**Issue by dfuchs1702** [Caleydo/ordino#179]
* Release number or git hash: 
* Web browser version and OS: OSX, Chrome
* Environment (local or deployed): 

### Steps to reproduce

1. Persistent Session 6
2. Collapsed Groups don't open on click (1st and 3rd group open, 2nd and 4th do not)

**Comment by mstreit** [comment]
duplicate of https://github.com/Caleydo/tdp_kuk_calumma/issues/4
