### ISSUE TITLE
Chart.js views only get a height of 150px

### ISSUE THREAD

**Issue by lehnerchristian** [Caleydo/ordino#193]
set view height to 100% to let Chart.js size the plots correctly

**Comment by sgratzl** [comment]
try again after https://github.com/Caleydo/ordino/commit/1c986c5fa79211c47609b8f0834f630123e446d7

**Comment by lehnerchristian** [comment]
the view size works, but Chart.js has this auto-resizing (wobbling) problem.

I think this is caused by the transition, but I'm not sure how to fix it properly
Do you have an idea how to fix it and can give me a hint?

**Comment by sgratzl** [comment]
see also https://bayer.githost.io/Target360/plugins/target360/blob/master/src/styles/_chartjs.scss#L33

**Comment by sgratzl** [comment]
fixed in https://github.com/datavisyn/tdp_publicdb_ext/commit/38aed2fbe933c58c01586363261538ee8b0e6f8b
