### ISSUE TITLE
Improve filter / score mapping dialog of numeric columns

### ISSUE THREAD

**Issue by zichner** [Caleydo/ordino#22]
At the moment, the dialog to filter numeric columns and to define the value mapping/scaling is a bit difficult to use and not very intuitive.

I propose the following changes
- [x] Indicate clearly that the upper part of the dialog is for value mapping/scaling and the lower for filtering
- [x] Indicate in the mapping/scaling part that the values at the top are the lineup scores and the ones at the bottom the raw/input values
- [x] If one clicks on a blue line or dot, show the current position as a value and let the user alter that value by typing a new value
- [ ] Add possibility to specify that "a blue dot" should be the minimum or maximum of the raw/input values
- [x] Add possibility to specify filter cutoffs by typing a numeric value
- [x] Clicking the reset button should set the filter/mapping parameters to the values they were when the column was added

**Comment by chrilehner** [comment]
I'm currently implementing the requested changes in the Mapping Filter but I'm not sure what you mean with bullet point 4, @zichner  ("Add possibility to specify that "a blue dot" should be the minimum or maximum of the raw/input values")

should the result of this specification be that a point moves to the leftmost or rightmost position, which would also be the result of dragging or using the new inputs (from point 3)

**Comment by zichner** [comment]
What I meant with point 4 is that it would be nice if one could assign a "blue dot" to the _current_ minimum or maximum of the raw/input values. By default, this indeed is the same as dragging the dot to the leftmost or rightmost position, however, there are two cases where this is different:
* If one filters the list of entities based on one column (e.g., only protein-coding genes), the range of existing values in a numeric column could also change (e.g., the copy number range of all genes could be 0 .. 10, but the range of protein coding genes is only 1 .. 4). In this case it would be nice if one can set the "blue dots" to the current extremes (here 1 .. 4).
* An additional but less important case: If one modified the value mapping boundaries to a value outside of the current range. For example: after adding a copy number score column, the range of raw values could be 0.5 to 3.4. If one changes this to 0 .. 4 it is currently not easy to get back to the original values afterwards (because now the leftmost position is 0 and not 0.5).

**Comment by chrilehner** [comment]
I talked to @sgratzl and point 4 is currently not possible. I'll create a separate issue with the suggestion

Furthermore, can you explain bullet point 6 further, @zichner ? E.g. the steps how I can reproduce and see the issue or with an example?

**Comment by zichner** [comment]
@chrilehner Bullet point 6 can be ignored (the described problem seems to not be present anymore).
