### ISSUE TITLE
Improve sample/gene selection in score dialog and detail views

### ISSUE THREAD

**Issue by zichner** [Caleydo/ordino#24]
In the 'add score' dialog as well as some detail views, one can select a set of samples/genes which should be used for the analysis.
Currently, this has several limitations (e.g., one cannot select a tissue panel + tumor type), therefore, I propose the following setup for the sample selection:

1. Select data source: `Cell line` or `Tissue`
2. Select filter criterion. Possible choices should be:
   - One or multiple entities selected by their ID
   - A tissue/cell line panel
   - A user defined 'named set'
   - Any categorical column of the tissue/cell line table (e.g., `Tumor Type` or `Organ`)
3. Select one or multiple values for the chosen criterion 
4. Redo step 2 and 3 if samples should be filtered further (different filter criteria are combined by `and` operator)

For the selection of genes, the steps are equivalent to the ones described for samples, however, the first step is not necessary.

In case this setup is too complicated/difficult, it should at least be possible to combine the selection of a cell line/tissue panel and a tumor type.

**Comment by sgratzl** [comment]
moved to internal repository
