### ISSUE TITLE
Override datavisyn logo from tdp_core with Caleydo logo

### ISSUE THREAD

**Issue by thinkh** [Caleydo/ordino#240]
We must test if Ordino still shows the Caleydo loading and header icon with the implementation of PR https://github.com/datavisyn/tdp_core/pull/276/.

![grafik](https://user-images.githubusercontent.com/5851088/79743651-3a098900-8305-11ea-95e5-b4e5f8d31c34.png)

1. Checkout tdp_core branch of PR https://github.com/datavisyn/tdp_core/pull/276/
2. Test which logo is shown (datavisyn or caleydo)

If the Caleydo is still shown there is nothing to do.

If the datavisyn logo is shown we must override this logo with the Caleydo logo.

1. Create a new _\_vars.scss_ file
2. Override the variables `$phovea-loading-icon` and `$tdp-busy-background`
3. Import the _\_vars.scss_ file in _/src/styles/ordino.scss_
4. Test again

Please also test the ordino_public and customer customizations.

**Comment by oltionchampari** [comment]
Tested the branch  datavisyn/tdp_core#276 with **ordino**, **ordino_public** , **tdp_bi_bioninfodb**, **tdp_genentech**. The correct logo and loader is shown.
