### ISSUE TITLE
single entity entry point

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/ordino#3]
In the current version, each session starts with a list of entities. However, starting with a single one would also be beneficial. like adding a search interface for ids and then showing a first view with detail information + the item is selected

**Comment by chrilehner** [comment]
Single Entry Point is now supported.

There are now 3 search fields inside the start menu:

![startmenu](https://cloud.githubusercontent.com/assets/1711080/23018564/b9320f8a-f43e-11e6-8767-b22b8087241b.png)

After typing the application instantly searches the database (e.g. for genes):

![startmenusearch](https://cloud.githubusercontent.com/assets/1711080/23018581/d0e8bc0a-f43e-11e6-93f8-fb364919d53b.png)

After selecting an element LineUp is instantiated with the selected element:

![singlegenerow](https://cloud.githubusercontent.com/assets/1711080/23018622/f509d646-f43e-11e6-8e7a-8bb54a88e0ca.png)

**Comment by mstreit** [comment]
Let's remove the additional label "Search gene" and just add the string "Search gene" inside the search box instead of "Start typing...".

**Comment by chrilehner** [comment]
Done. See 279b012114427db1dfba8a712738937283e19fef and f96ba74a63c82171e7c3df020fe0cdfd56fe8cdc
