### ISSUE TITLE
cache values of score columns of current session in addition to the parameters

### ISSUE THREAD

**Issue by mstreit** [Caleydo/ordino#35]
If the user jumps around between states of the current session, we now on the fly recalculate all scores using the stored parameters. Re-calculating scores can potentially take a long time. To speed this up, we could temporarily store the actual scoring results in the provenance graph for the current session.

**Comment by sgratzl** [comment]
we can locally cache it in the browser and server side (see #47) but not in the provenance graph since it would be persistent

**Comment by sgratzl** [comment]
see also #72 it is now configured that requested data from the database (like all of your scores) are cached by the browser itself for 6h. So (needs to be tested) no need for caching it again
