### ISSUE TITLE
Add multiple gene selector for internal GeneHopper LineUp

### ISSUE THREAD

**Issue by mstreit** [Caleydo/ordino#39]
If the user selects multiple genes in LineUp only the last one will be shown as GeneHopper LineUp. As in the other detail views the user should be able to select the gene that is shown.

![image](https://cloud.githubusercontent.com/assets/4129755/24038864/843b5846-0b03-11e7-96cd-51b4975449a0.png)

**Comment by zichner** [comment]
FYI: According to #20, this issue was moved to the internal repository, but I could not find it there.

**Comment by mstreit** [comment]
It's here: https://github.com/Caleydo/targid_genehopper/issues/7
I am closing this one.
