### ISSUE TITLE
LineUp Filter/Score Mapping

### ISSUE THREAD

**Issue by lehnerchristian** [Caleydo/ordino#52]
coming from #22 point 4 and https://github.com/Caleydo/ordino/issues/22#issuecomment-290381758:

When one column in LineUp and then trying to filter another column the second column should have the new domain as the boundaries (without the filtered rows)

E.g. when column B has a domain from [0, 10] and column A is filtered first, the remaining rows of column B could have the domain [1, 3]. when opening the filter dialog the domain of column B should be [1, 3] instead of the original [0, 10]

**Comment by sgratzl** [comment]
moved to https://github.com/datavisyn/tdp_core/issues/15
