### ISSUE TITLE
Detail views that use HTTP links don't work in public ordino instance

### ISSUE THREAD

**Issue by mstreit** [Caleydo/ordino#58]
As Ordino public is secured via https, http detail view links don't work. 

Error message:
```
Mixed Content: The page at 'https://ordino-daily.caleydoapp.org/#clue_graph=workspaceForOrdinoGcl8M&clue_state=11' was loaded over HTTPS, but requested an insecure resource 'http://feb2014.archive.ensembl.org/human/Gene/Summary?g=ENSG00000146648'. This request has been blocked; the content must be served over HTTPS.
```

Any ideas how to solve this?

**Comment by sgratzl** [comment]
we could proxy all the pages through our server

**Comment by sgratzl** [comment]
won't work, since the integrated page has also other links which are then insecure,...

**Comment by mstreit** [comment]
we could open external https pages in a new window.

**Comment by sgratzl** [comment]
if the pages would support https, I would use it but, e.g. [Ensembl](https://feb2014.archive.ensembl.org/human/Gene/Summary?g=ENSG00000146648) gives me a browser warning

**Comment by lehnerchristian** [comment]
I think opening in a new window / tab is a valid solution. not very nice since some detail views would be embedded in ordino and others would open tabs, but should work

when I go to the HTTPS version of the new Ensembl.org mirror (https://www.ensembl.org/index.html), I get to the page, but without JS or CSS, since they are again served via HTTP and blocked by the browser...

**Comment by lehnerchristian** [comment]
we could use @mstreit 's idea for the moment and email the sites to fix their HTTPS certificates or how their resources are loaded
I think it would be in their interest to fix this problem

**Comment by mstreit** [comment]
as @sgratzl wrote, I also get a warning when I open the ENSEMBL page via https. but once I confirm that this is secure, it seems to work. wouldn't that be a better solution than external windows?

**Comment by mstreit** [comment]
I am sure those big portal developers know about this issue (and have their reasons why they don't use https at the moment).

**Comment by sgratzl** [comment]
I'm not sure whether it works with embedded iframes, too. 

so the idea is to detect in a proxy page whether the the protocol is less secure and if so, provide a helper text ala: 
>Ordino uses HTTPS to secure your communication with our server. However, the requested external website doesn't support HTTPS. Thus cannot be directly embedded in Ordino. Please use this LINK to open the website in a separate window.

**Comment by mstreit** [comment]
OK, sounds good.
