### ISSUE TITLE
Add "for research purpose only" disclaimer

### ISSUE THREAD

**Issue by mstreit** [Caleydo/ordino#60]

**Comment by mstreit** [comment]
https://www.genomeweb.com/clinical-genomics/fda-releases-guidance-research-use-investigational-use-only-ivds

**Comment by sgratzl** [comment]
![greenshot_2017-04-28_15-05-57](https://cloud.githubusercontent.com/assets/4129778/25529924/7c003ace-2c24-11e7-980e-f550494c4a71.png)
