### ISSUE TITLE
Select2: show first n AJAX results without typing letters

### ISSUE THREAD

**Issue by chrilehner** [Caleydo/ordino#61]
e.g. first 10 results

**Comment by thinkh** [comment]
@chrilehner I created a [CodePen](https://codepen.io/thinkh/pen/bWxPrG?editors=0010) for you.
On focus shows the initial list of items and when typing a regular ajax request is sent.
I implemented a custom `ajax.transport` function and set the `minimumInputLength: 0`

**Comment by mstreit** [comment]
Nice. Let's set this in all filter and search select2 fields (scores, welcome page).

**Comment by sgratzl** [comment]
since we also want the initial options via ajax, why not just setting: `minimumInputLength=0` and that's it?

**Comment by chrilehner** [comment]
works like a charm
I already pushed this minimal change to develop
see https://github.com/Caleydo/ordino/commit/3f10d713ca4b593bc513aaa9c5bbebc642b7611e
