### ISSUE TITLE
Improve performance of boxplot DB queries

### ISSUE THREAD

**Issue by zichner** [Caleydo/ordino#8]
For boxplot columns, `min`, `max`, `median`, `q1`, and `q3` are queried in 5 separate `percentile_cont()` calls.
The performance of these DB queries can be improved by ~10% if the `percentile_cont()` calls are combined into a single call, e.g., something like:

```
SELECT 
  ensg AS id, 
  percentile_cont(ARRAY[0, 0.25, 0.5, 0.75, 1]) WITHIN GROUP (ORDER BY xxx) as p 
FROM xxx 
WHERE celllinename = ANY(...) GROUP BY ensg;
```

**Comment by zichner** [comment]
FYI: the 10% speed up I saw might have been due to caching. So, it is not entirely clear whether the query above is really faster. Some further testing is needed.

**Comment by sgratzl** [comment]
part of https://github.com/Caleydo/targid_boehringer/pull/412
