### ISSUE TITLE
define intelligent predefined named sets in public database

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/ordino#84]
e.g. protein coding genes

**Comment by sgratzl** [comment]
atm. we have just all, e.g. 60k entries which is a huge slow down for the whole app and scores.

**Comment by mstreit** [comment]
That's something a Bioinformatician needs to define. I suggest to ask Thomas.

**Comment by zichner** [comment]
For now we can use the same ones as we have internally, except for "Driver Kinases" and those for which we do not have any samples in the public version.
@awernibi Are the sample and gene sets already contained in the public Ordino DB? If not, can you please add them? Thanks!

**Comment by awernibi** [comment]
Now we have all three: celllinepanels, tissuepanels (was already there), and genesets.

```
ordino=> select celllinepanel, count(*) from cellline.celllineassignment group by celllinepanel;
 celllinepanel | count 
---------------+-------
 Xenografts    |    71
 CCLE          |  1009
 Ricerca60     |    52
 Ricerca240    |   192
 Eurofins320   |   246
 NCI-60        |    49
(6 rows)

ordino=> select tissuepanel, count(*) from tissue.tissueassignment group by tissuepanel;
 tissuepanel  | count 
--------------+-------
 TCGA normals |   736
 TCGA tumors  |  9887
(2 rows)

ordino=> select genesetname, count(*) from geneassignment group by genesetname;
                 genesetname                  | count 
----------------------------------------------+-------
 normal chromosome protein coding human genes | 20415
 driver kinases doi:10.1038/nrc.2015.18       |    91
(2 rows)

```

**Comment by zichner** [comment]
Thanks!
Do you think we need the driver kinases gene list?
Or the other way around, if we have this list, should we also add other gene lists of potential interest ("antibodyome", etc)

**Comment by awernibi** [comment]
Yes, I think we should keep the driver kinases. I added the Cancer Gene Census (from COSMIC) and I am scanning for additional gene sets.
