### ISSUE TITLE
Public saved set is listed under my sets

### ISSUE THREAD

**Issue by mstreit** [Caleydo/ordino#88]
When saving a gene set on the welcome page it is listed under my sets although I've ticket the "public" option in the save dialog.

![image](https://user-images.githubusercontent.com/4129755/27352573-6e643ecc-5601-11e7-814d-6f576b2c8c50.png)

**Comment by sgratzl** [comment]
yes, because it is still yours - similar to my and public others

**Comment by mstreit** [comment]
Aha OK, this makes sense. So I cannot find out later on if my set/data set/session is public or not, right?

**Comment by sgratzl** [comment]
the others have the public/private icon in their list. However, this is missing for the named sets so far

**Comment by sgratzl** [comment]
successor issue: #91
