### ISSUE TITLE
Show gene symbol in addition to ENSEMBL ID in detail view options dropdown

### ISSUE THREAD

**Issue by mstreit** [Caleydo/ordino#89]
![image](https://user-images.githubusercontent.com/4129755/27353048-ffb024c6-5602-11e7-9d1c-fb221dc4f4fa.png)

I would expect to see the same as in the "Co-Expression" detail view when switching the reference gene:
![image](https://user-images.githubusercontent.com/4129755/27353226-9fef48ea-5603-11e7-8791-85aab8e2c04e.png)

This should be consistent across all detail views that let the user switch between the entity via the dropdown.

**Comment by sgratzl** [comment]
Co Expression in Bien, doesn't show Genes but ProbeSets

**Comment by mstreit** [comment]
Yes, for BIEN co-expression it shows the gene symbol and the probeset ID.
![image](https://user-images.githubusercontent.com/4129755/27354019-700a7174-5606-11e7-9e02-9a149e97a61e.png)
 
But what about the other detail views - like external link detail views?

**Comment by sgratzl** [comment]
should be solved due to the same reason as in #528

**Comment by lehnerchristian** [comment]
I think the only detail view that is currently not showing `GeneSymbol (ENSEMBL)` or `GeneSymbol (PROBESET_ID)` is the Expression Detail view inside the `BIEN Details` group

**Comment by thinkh** [comment]
Closed since we don't support BIEN anymore.
