### ISSUE TITLE
Automatically identify IDTypes on import

### ISSUE THREAD

**Issue by chrilehner** [Caleydo/ordino#9]
IDTypes should be identified when importing a dataset automatically.

Genes: Ensembl ID (beginning with ENSG)
Cell Lines & Tissues: query database

First the columns are searched for the string "ENSG" to find Ensembl IDs. If a column with these substrings is found, it is considered as the ID column.

Otherwise the database is queried to find the IDs (e.g. for cell lines & tissues). If the IDs are found, this column is considered as the ID column again.

**Comment by chrilehner** [comment]
Auto detection for IDTypes works now:

![file_import](https://cloud.githubusercontent.com/assets/1711080/23178675/a2bcf2e8-f86b-11e6-8351-fb34cbc87035.gif)

**Comment by chrilehner** [comment]
Auto detection of IDTypes works now:

![file_import](https://cloud.githubusercontent.com/assets/1711080/23179087/0147055a-f86d-11e6-81c5-ceb78a7ea870.gif)

**Comment by chrilehner** [comment]
When multiple IDTypes are identified, the first one is treated as IDType and all subsequent are treated as string columns

**Comment by mstreit** [comment]
Not necessarily as string column. There could also be ID types in the future that are just numbers. In this case the additional columns should also be detected as numerical data.

**Comment by sgratzl** [comment]
I would leave the string, since they are still identifiers. Otherwise the user can change it

**Comment by mstreit** [comment]
OK

**Comment by chrilehner** [comment]
![importer](https://cloud.githubusercontent.com/assets/1711080/23754179/53b5bbb2-04dc-11e7-81ea-b63bc4b57257.gif)
