### ISSUE TITLE
Add "number" visualization to numerical score column visualizations

### ISSUE THREAD

**Issue by mstreit** [Caleydo/ordino#90]
At the moment we offer bar and circle. It would make a lot of sense to let the user switch to a number/string representation.

![image](https://user-images.githubusercontent.com/4129755/27354474-fe837742-5607-11e7-82e6-b63544a2dc6f.png)

**Comment by sgratzl** [comment]
should be done with https://github.com/Caleydo/lineupjs/commit/3e5efa5e06fe3f0c0cafdcee5c6b02c5758f1ca7
