### ISSUE TITLE
Nothing happens when trying to calculate an aggregated score

### ISSUE THREAD

**Issue by lehnerchristian** [Caleydo/ordino#92]
Happens in the latest deployed dev versions

### Steps to reproduce

1. Load a Cell Line list
2. Click the + icon to add an aggregated score column
3. Set the filter (e.g. BioType: miRNA)
4. click the "Add Aggregated Score Column" button

### Observed behavior
* nothing happens (Chrome logs `An invalid form control with name='' is not focusable.` in the console)

### Expected behavior
* calculation of aggregated scores

**Comment by sgratzl** [comment]
solved with https://github.com/Caleydo/ordino/commit/5a7a059e9559e3f17f19d12846ee911534fff4f2

background: 
 the field for specifying the comparison value is required but not visible. I provided now an intelligent default
