### ISSUE TITLE
add advanced multi column scores

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/ordino#98]
e.g. ScriptColumn, Min, Max

**Comment by sgratzl** [comment]
added ScriptedColumn for now

**Comment by zichner** [comment]
Can you please post an example of how the ScriptedColumn can be used?

**Comment by sgratzl** [comment]
see https://github.com/Caleydo/lineupjs/pull/287

**Comment by zichner** [comment]
Thanks!
How would I for instance get the maximum of two columns of interest?

**Comment by sgratzl** [comment]
> How would I for instance get the maximum of two columns of interest?

beware of https://github.com/Caleydo/lineupjs/issues/285

![scripted_column](https://user-images.githubusercontent.com/4129778/28768593-8ca3cf46-75d8-11e7-8bcd-7cf8835a3723.gif)
